-- DUMMY DATA GENERATION SCRIPT FOR PORTL
-- RUN THIS IN THE SUPABASE SQL EDITOR (DASHBOARD)

-- Enable pgcrypto extension if not already enabled (needed for crypt/gen_salt)
CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA extensions;

-- Wrap in a transaction block so everything is created together
BEGIN;

-- CLEANUP SECTION
-- WARNING: This deletes previous dummy data generated by this script to allow clean reruns
DELETE FROM public.poll_comments WHERE profile_id IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com');
DELETE FROM public.poll_votes WHERE profile_id IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com');
DELETE FROM public.polls WHERE created_by IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com');

DELETE FROM public.notice_reads WHERE profile_id IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com');
DELETE FROM public.notice_reactions WHERE profile_id IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com');
DELETE FROM public.notices WHERE created_by IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com');

DELETE FROM public.amenity_bookings WHERE profile_id IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com');

DELETE FROM public.complaint_updates WHERE profile_id IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com');
DELETE FROM public.complaints WHERE raised_by IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com');

DELETE FROM public.visitors WHERE guard_id IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com') 
   OR decided_by IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com')
   OR flat_id IN (SELECT flat_id FROM public.flat_residents WHERE profile_id IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com'));
DELETE FROM public.pre_approvals WHERE created_by_profile_id IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com');

DELETE FROM public.sos_alerts WHERE created_by IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com');
DELETE FROM public.frequent_visitors WHERE profile_id IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com');

DELETE FROM public.vehicles WHERE flat_id IN (SELECT flat_id FROM public.flat_residents WHERE profile_id IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com'));
DELETE FROM public.family_members WHERE profile_id IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com');

DELETE FROM public.dues WHERE flat_id IN (SELECT flat_id FROM public.flat_residents WHERE profile_id IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com'));
DELETE FROM public.payments WHERE profile_id IN (SELECT id FROM public.profiles WHERE phone LIKE '+91990000%' OR email LIKE '%@portldummy.com');

-- Finally, delete the dummy users (this cascades to profiles and flat_residents)
DELETE FROM auth.users WHERE email LIKE '%@portldummy.com' OR phone LIKE '+91990000%';

-- DECLARE AND EXECUTE ANONYMOUS PL/PGSQL BLOCK TO GENERATE DATA FOR DEMO SOCIETY
DO $$
DECLARE
  -- Target existing Prestige Meadows society from seed.sql
  v_society_id uuid := '11111111-1111-1111-1111-111111111111';
  
  -- Name databases for randomization
  first_names text[] := ARRAY['Aarav', 'Ananya', 'Amit', 'Deepika', 'Rahul', 'Pooja', 'Vikram', 'Neha', 'Rohan', 'Sneha', 'Kabir', 'Aditi', 'Rajesh', 'Kiran', 'Sanjay', 'Geeta', 'Vijay', 'Sunita', 'Arjun', 'Meera', 'Dev', 'Kavita', 'Ravi', 'Ritu', 'Abhishek', 'Swati', 'Alok', 'Preeti', 'Manoj', 'Anjali'];
  last_names text[] := ARRAY['Sharma', 'Verma', 'Gupta', 'Patel', 'Joshi', 'Mehra', 'Singh', 'Kumar', 'Shah', 'Rao', 'Nair', 'Iyer', 'Reddy', 'Choudhury', 'Das', 'Sen', 'Bose', 'Mishra', 'Trivedi', 'Pandey', 'Saxena', 'Kapoor', 'Malhotra', 'Bhatia', 'Kohli', 'Gill', 'Jadhav', 'Kulkarni', 'Deshmukh', 'Pillai'];
  
  -- Iterators & Holders
  f_id uuid;
  flat_ids uuid[] := '{}';
  flat_count int;
  
  -- Users
  v_user_id uuid;
  v_spouse_id uuid;
  v_admin_id uuid;
  v_guard_id uuid;
  v_email text;
  v_name text;
  v_phone text;
  
  resident_profile_ids uuid[] := '{}';
  guard_profile_ids uuid[] := '{}';
  admin_profile_ids uuid[] := '{}';
  
  -- Vehicle
  v_vehicle_count int;
  v_vehicle_type text;
  v_vehicle_model text;
  v_vehicle_color text;
  v_plate text;
  
  -- Family
  v_family_count int;
  v_relation text;
  v_family_name text;
  v_age int;
  
  -- Pre-approvals & Visitors
  v_visitor_type visitor_type;
  v_code text;
  v_status visitor_status;
  v_requested_at timestamptz;
  v_entered_at timestamptz;
  v_exited_at timestamptz;
  
  -- Notice/Polls/Amenities
  n_id uuid;
  p_id uuid;
  am_id uuid;
  c_id uuid;
  v_title text;
  v_category text;
  v_desc text;
  v_priority complaint_priority;
  v_status complaint_status;
  
  -- Dues/Payments
  v_period date;
  v_due_date date;
  v_electricity numeric;
  v_maintenance numeric;
  v_total_amount numeric;
  v_line_items jsonb;
  v_due_status dues_status;
  v_payment_id uuid;
  v_order_id text;
  v_razorpay_id text;
  
BEGIN
  -- 1. Fetch all flats from Prestige Meadows
  SELECT array_agg(id) INTO flat_ids
  FROM public.flats
  WHERE tower_id IN (
    SELECT id FROM public.towers WHERE society_id = v_society_id
  );
  
  flat_count := array_length(flat_ids, 1);
  IF flat_count IS NULL OR flat_count = 0 THEN
    RAISE EXCEPTION 'Demo society flats not found. Please run seed.sql first!';
  END IF;

  -- 2. Generate Admins (2 admins)
  FOR i IN 1..2 LOOP
    v_user_id := gen_random_uuid();
    v_email := 'admin.' || i || '@portldummy.com';
    v_name := first_names[1 + floor(random() * array_length(first_names, 1))::int] || ' ' || last_names[1 + floor(random() * array_length(last_names, 1))::int];
    v_phone := '+91990000100' || i;
    
    INSERT INTO auth.users (id, instance_id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, role, aud, created_at, updated_at, phone, phone_confirmed_at)
    VALUES (v_user_id, '00000000-0000-0000-0000-000000000000', v_email, extensions.crypt('password123', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}'::jsonb, jsonb_build_object('full_name', v_name), false, 'authenticated', 'authenticated', now(), now(), v_phone, now());

    INSERT INTO public.profiles (id, society_id, full_name, phone, role, status)
    VALUES (v_user_id, v_society_id, v_name, v_phone, 'admin', 'active');
    
    admin_profile_ids := array_append(admin_profile_ids, v_user_id);
  END LOOP;

  -- 3. Generate Guards (4 guards)
  FOR i IN 1..4 LOOP
    v_user_id := gen_random_uuid();
    v_email := 'guard.' || i || '@portldummy.com';
    v_name := first_names[1 + floor(random() * array_length(first_names, 1))::int] || ' ' || last_names[1 + floor(random() * array_length(last_names, 1))::int];
    v_phone := '+91990000200' || i;
    
    INSERT INTO auth.users (id, instance_id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, role, aud, created_at, updated_at, phone, phone_confirmed_at)
    VALUES (v_user_id, '00000000-0000-0000-0000-000000000000', v_email, extensions.crypt('password123', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}'::jsonb, jsonb_build_object('full_name', v_name), false, 'authenticated', 'authenticated', now(), now(), v_phone, now());

    INSERT INTO public.profiles (id, society_id, full_name, phone, role, status)
    VALUES (v_user_id, v_society_id, v_name, v_phone, 'guard', 'active');
    
    guard_profile_ids := array_append(guard_profile_ids, v_user_id);
  END LOOP;

  -- 4. Generate Residents for ~75% of flats (up to 60 flats)
  FOR i IN 1..least(60, flat_count) LOOP
    f_id := flat_ids[i];
    
    -- Primary Resident (Head of Flat)
    v_user_id := gen_random_uuid();
    v_email := 'resident.' || i || '.1@portldummy.com';
    v_name := first_names[1 + floor(random() * array_length(first_names, 1))::int] || ' ' || last_names[1 + floor(random() * array_length(last_names, 1))::int];
    v_phone := '+919900003' || lpad(i::text, 2, '0') || '1';
    
    INSERT INTO auth.users (id, instance_id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, role, aud, created_at, updated_at, phone, phone_confirmed_at)
    VALUES (v_user_id, '00000000-0000-0000-0000-000000000000', v_email, extensions.crypt('password123', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}'::jsonb, jsonb_build_object('full_name', v_name), false, 'authenticated', 'authenticated', now(), now(), v_phone, now());

    INSERT INTO public.profiles (id, society_id, full_name, phone, role, status)
    VALUES (v_user_id, v_society_id, v_name, v_phone, 'resident', 'active');

    INSERT INTO public.flat_residents (flat_id, profile_id, is_owner, is_head)
    VALUES (f_id, v_user_id, true, true);
    
    resident_profile_ids := array_append(resident_profile_ids, v_user_id);
    
    -- 50% chance of a second resident (spouse/roommate) in same flat
    IF random() < 0.5 THEN
      v_spouse_id := gen_random_uuid();
      v_email := 'resident.' || i || '.2@portldummy.com';
      v_name := first_names[1 + floor(random() * array_length(first_names, 1))::int] || ' ' || last_names[1 + floor(random() * array_length(last_names, 1))::int];
      v_phone := '+919900003' || lpad(i::text, 2, '0') || '2';
      
      INSERT INTO auth.users (id, instance_id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, role, aud, created_at, updated_at, phone, phone_confirmed_at)
      VALUES (v_spouse_id, '00000000-0000-0000-0000-000000000000', v_email, extensions.crypt('password123', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}'::jsonb, jsonb_build_object('full_name', v_name), false, 'authenticated', 'authenticated', now(), now(), v_phone, now());

      INSERT INTO public.profiles (id, society_id, full_name, phone, role, status)
      VALUES (v_spouse_id, v_society_id, v_name, v_phone, 'resident', 'active');

      INSERT INTO public.flat_residents (flat_id, profile_id, is_owner, is_head)
      VALUES (f_id, v_spouse_id, true, false);
      
      resident_profile_ids := array_append(resident_profile_ids, v_spouse_id);
    END IF;
    
    -- Generate vehicles (1 or 2 vehicles per flat)
    v_vehicle_count := (1 + floor(random() * 2))::int;
    FOR j IN 1..v_vehicle_count LOOP
      v_vehicle_type := (ARRAY['Car', 'Bike'])[1 + floor(random() * 2)::int];
      IF v_vehicle_type = 'Car' THEN
        v_vehicle_model := (ARRAY['Honda City', 'Hyundai Creta', 'Maruti Swift', 'Tata Nexon', 'Toyota Fortuner'])[1 + floor(random() * 5)::int];
        v_vehicle_color := (ARRAY['White', 'Silver', 'Black', 'Red', 'Grey'])[1 + floor(random() * 5)::int];
      ELSE
        v_vehicle_model := (ARRAY['Royal Enfield Classic', 'Honda Activa', 'TVS Jupiter', 'Bajaj Pulsar', 'Hero Splendor'])[1 + floor(random() * 5)::int];
        v_vehicle_color := (ARRAY['Black', 'Blue', 'Red', 'Grey'])[1 + floor(random() * 4)::int];
      END IF;
      
      v_plate := 'MH12' || (ARRAY['AB', 'CD', 'EF', 'GH', 'KL'])[1 + floor(random() * 5)::int] || lpad((1000 + floor(random() * 8999)::int)::text, 4, '0');
      
      INSERT INTO public.vehicles (flat_id, type, plate_number, color, model)
      VALUES (f_id, v_vehicle_type, v_plate, v_vehicle_color, v_vehicle_model);
    END LOOP;
    
    -- Generate Family Members (0 to 2 per flat)
    v_family_count := floor(random() * 3)::int;
    FOR j IN 1..v_family_count LOOP
      v_relation := (ARRAY['Child', 'Parent'])[1 + floor(random() * 2)::int];
      v_family_name := first_names[1 + floor(random() * array_length(first_names, 1))::int] || ' ' || last_names[1 + floor(random() * array_length(last_names, 1))::int];
      IF v_relation = 'Child' THEN
        v_age := (2 + floor(random() * 16))::int;
      ELSE
        v_age := (50 + floor(random() * 30))::int;
      END IF;
      
      INSERT INTO public.family_members (profile_id, name, relation, age, flat_id)
      VALUES (v_user_id, v_family_name, v_relation, v_age, f_id);
    END LOOP;
  END LOOP;

  -- 5. Generate Pre-approvals (15 entries)
  FOR i IN 1..15 LOOP
    SELECT flat_id, profile_id INTO f_id, v_user_id
    FROM public.flat_residents
    ORDER BY random()
    LIMIT 1;
    
    v_name := (ARRAY['Delivery Agent', 'John Doe', 'Electrician Ram', 'Uber Cab', 'Amazon Delivery'])[1 + floor(random() * 5)::int];
    v_phone := '+9198765' || lpad((10000 + floor(random() * 89999)::int)::text, 5, '0');
    v_visitor_type := (ARRAY['delivery', 'guest', 'service', 'cab'])[1 + floor(random() * 4)::int]::visitor_type;
    v_code := UPPER(substring(md5(random()::text) from 1 for 6));
    
    INSERT INTO public.pre_approvals (flat_id, created_by_profile_id, visitor_name, visitor_phone, type, start_at, end_at, code, notes)
    VALUES (f_id, v_user_id, v_name, v_phone, v_visitor_type, now() - interval '1 day', now() + interval '2 days', v_code, 'Please ring bell');
  END LOOP;

  -- 6. Generate Visitors (30 entries with different statuses)
  FOR i IN 1..30 LOOP
    SELECT flat_id, profile_id INTO f_id, v_user_id
    FROM public.flat_residents
    ORDER BY random()
    LIMIT 1;

    v_name := (ARRAY['Courier Boy', 'Zomato Rider', 'Aunt Meena', 'Plumber Shyam', 'Ola Driver', 'Friend Vikram'])[1 + floor(random() * 6)::int];
    v_phone := '+9187654' || lpad((10000 + floor(random() * 89999)::int)::text, 5, '0');
    v_visitor_type := (ARRAY['delivery', 'delivery', 'guest', 'service', 'cab', 'guest'])[1 + floor(random() * 6)::int]::visitor_type;
    
    v_status := (ARRAY['entered', 'exited', 'pending', 'approved', 'rejected'])[1 + floor(random() * 5)::int]::visitor_status;
    
    IF v_status = 'exited' THEN
      v_requested_at := now() - (floor(random() * 5)::int || ' days ' || floor(random() * 12)::int || ' hours')::interval;
      v_entered_at := v_requested_at + interval '5 minutes';
      v_exited_at := v_entered_at + (30 + floor(random() * 120)::int || ' minutes')::interval;
    ELSIF v_status = 'entered' THEN
      v_requested_at := now() - (floor(random() * 4)::int || ' hours')::interval;
      v_entered_at := v_requested_at + interval '5 minutes';
      v_exited_at := NULL;
    ELSIF v_status = 'approved' THEN
      v_requested_at := now() - (floor(random() * 30)::int || ' minutes')::interval;
      v_entered_at := NULL;
      v_exited_at := NULL;
    ELSIF v_status = 'rejected' THEN
      v_requested_at := now() - (floor(random() * 2)::int || ' hours')::interval;
      v_entered_at := NULL;
      v_exited_at := NULL;
    ELSE -- pending
      v_requested_at := now() - (floor(random() * 15)::int || ' minutes')::interval;
      v_entered_at := NULL;
      v_exited_at := NULL;
    END IF;

    -- Pick a random guard
    v_guard_id := guard_profile_ids[1 + floor(random() * array_length(guard_profile_ids, 1))::int];
    
    INSERT INTO public.visitors (
      society_id, flat_id, visitor_name, visitor_phone, type, purpose, status, 
      guard_id, requested_at, entered_at, exited_at, decided_by, decided_at, guard_note
    )
    VALUES (
      v_society_id, f_id, v_name, v_phone, v_visitor_type, 'Delivery/Meeting', v_status,
      v_guard_id, v_requested_at, v_entered_at, v_exited_at, 
      CASE WHEN v_status IN ('approved', 'rejected', 'entered', 'exited') THEN v_user_id ELSE NULL END,
      CASE WHEN v_status IN ('approved', 'rejected', 'entered', 'exited') THEN v_requested_at + interval '2 minutes' ELSE NULL END,
      'Verified at main gate'
    );
  END LOOP;

  -- 7. Generate Frequent Visitors (1 per resident)
  FOR i IN 1..array_length(resident_profile_ids, 1) LOOP
    v_user_id := resident_profile_ids[i];
    
    v_name := (ARRAY['Maid Sunita', 'Driver Ramesh', 'Milkman Milkha', 'Cook Kavita'])[1 + floor(random() * 4)::int];
    v_phone := '+9177000' || lpad((10000 + floor(random() * 89999)::int)::text, 5, '0');
    v_visitor_type := (ARRAY['service', 'service', 'delivery', 'service'])[1 + floor(random() * 4)::int]::visitor_type;
    
    INSERT INTO public.frequent_visitors (profile_id, visitor_name, visitor_phone, visitor_type)
    VALUES (v_user_id, v_name, v_phone, v_visitor_type)
    ON CONFLICT DO NOTHING;
  END LOOP;

  -- 8. Generate Notices (4 board announcements)
  v_admin_id := admin_profile_ids[1];
  
  -- AGM Meeting
  INSERT INTO public.notices (society_id, category, title, body, pinned, created_by, published_at)
  VALUES (
    v_society_id, 
    'general', 
    'Annual General Meeting (AGM) 2026', 
    'Dear Residents, the AGM for this year is scheduled for next Sunday at 10:00 AM in the Clubhouse. Attendance is highly requested as we will vote on the new maintenance budget.', 
    true, 
    v_admin_id, 
    now() - interval '2 days'
  ) RETURNING id INTO n_id;
  
  FOR i IN 1..array_length(resident_profile_ids, 1) LOOP
    v_user_id := resident_profile_ids[i];
    INSERT INTO public.notice_reads (notice_id, profile_id, read_at) VALUES (n_id, v_user_id, now() - interval '1 day');
    IF random() < 0.3 THEN
      INSERT INTO public.notice_reactions (notice_id, profile_id, emoji) VALUES (n_id, v_user_id, '👍');
    END IF;
  END LOOP;

  -- Water Shutdown
  INSERT INTO public.notices (society_id, category, title, body, pinned, created_by, published_at)
  VALUES (
    v_society_id, 
    'maintenance', 
    'Water Supply Interruption - Tower B & C', 
    'Please note that there will be a scheduled water shutdown on Wednesday from 10:00 AM to 2:00 PM due to overhead tank cleaning. Please store water in advance.', 
    false, 
    v_admin_id, 
    now() - interval '1 day'
  ) RETURNING id INTO n_id;
  
  -- Independence Day Celebration
  INSERT INTO public.notices (society_id, category, title, body, pinned, created_by, published_at)
  VALUES (
    v_society_id, 
    'event', 
    'Independence Day Celebrations 2026', 
    'Join us for flag hoisting followed by breakfast and cultural events in the main courtyard starting at 8:30 AM on August 15th.', 
    false, 
    v_admin_id, 
    now()
  ) RETURNING id INTO n_id;

  -- Fire Safety
  INSERT INTO public.notices (society_id, category, title, body, pinned, created_by, published_at)
  VALUES (
    v_society_id, 
    'emergency', 
    'Mandatory Fire Safety Drill', 
    'A society-wide fire drill will be conducted by the local fire department this Saturday at 4:00 PM. Please follow security instructions.', 
    true, 
    v_admin_id, 
    now() - interval '5 hours'
  ) RETURNING id INTO n_id;

  -- 9. Generate Polls (2 polls with votes and comments)
  -- Poll 1: Pet Policy
  INSERT INTO public.polls (
    society_id, category, question, options, allow_multiple, anonymous, show_results, ends_at, created_by
  ) VALUES (
    v_society_id,
    'rules',
    'Should we restrict pet walking in the main central park area?',
    '["Yes, completely restrict", "No, keep it open", "Restrict only during peak hours (6-8 AM/PM)"]'::jsonb,
    false,
    false,
    true,
    now() + interval '5 days',
    v_admin_id
  ) RETURNING id INTO p_id;
  
  FOR i IN 1..array_length(resident_profile_ids, 1) LOOP
    v_user_id := resident_profile_ids[i];
    IF random() < 0.8 THEN
      INSERT INTO public.poll_votes (poll_id, profile_id, option_indices, voted_at)
      VALUES (p_id, v_user_id, ARRAY[(floor(random() * 3))::int], now() - interval '1 day');
    END IF;
    
    IF random() < 0.15 THEN
      INSERT INTO public.poll_comments (poll_id, profile_id, body)
      VALUES (p_id, v_user_id, (ARRAY['We should have a dedicated pet park area.', 'Peak hours restriction is the best balance.', 'Why restrict? Central park is for everyone.'])[1 + floor(random() * 3)::int]);
    END IF;
  END LOOP;

  -- Poll 2: Gym Timing
  INSERT INTO public.polls (
    society_id, category, question, options, allow_multiple, anonymous, show_results, ends_at, created_by
  ) VALUES (
    v_society_id,
    'amenities',
    'What should be the Gym opening hours in the morning?',
    '["5:00 AM - 10:00 AM", "6:00 AM - 11:00 AM", "Open 24/7 (CCTV monitored)"]'::jsonb,
    false,
    true,
    true,
    now() + interval '3 days',
    v_admin_id
  ) RETURNING id INTO p_id;
  
  FOR i IN 1..array_length(resident_profile_ids, 1) LOOP
    v_user_id := resident_profile_ids[i];
    IF random() < 0.7 THEN
      INSERT INTO public.poll_votes (poll_id, profile_id, option_indices, voted_at)
      VALUES (p_id, v_user_id, ARRAY[(floor(random() * 3))::int], now() - interval '12 hours');
    END IF;
  END LOOP;

  -- 10. Generate Amenity Bookings (using existing seeded amenities)
  -- Fetch seeded amenities for Prestige Meadows
  SELECT id INTO am_id FROM public.amenities WHERE society_id = v_society_id AND name = 'Community Hall' LIMIT 1;
  IF am_id IS NOT NULL THEN
    FOR i IN 1..5 LOOP
      SELECT flat_id, profile_id INTO f_id, v_user_id FROM public.flat_residents ORDER BY random() LIMIT 1;
      INSERT INTO public.amenity_bookings (amenity_id, profile_id, flat_id, start_at, end_at, total_amount, deposit, status)
      VALUES (
        am_id, 
        v_user_id, 
        f_id, 
        date_trunc('day', now() + (i * 2 || ' days')::interval) + interval '10 hours', 
        date_trunc('day', now() + (i * 2 || ' days')::interval) + interval '16 hours', 
        3000.00, 
        1000.00, 
        'confirmed'
      );
    END LOOP;
  END IF;

  SELECT id INTO am_id FROM public.amenities WHERE society_id = v_society_id AND name = 'Swimming Pool' LIMIT 1;
  IF am_id IS NOT NULL THEN
    FOR i IN 1..5 LOOP
      SELECT flat_id, profile_id INTO f_id, v_user_id FROM public.flat_residents ORDER BY random() LIMIT 1;
      INSERT INTO public.amenity_bookings (amenity_id, profile_id, flat_id, start_at, end_at, total_amount, deposit, status)
      VALUES (
        am_id, 
        v_user_id, 
        f_id, 
        date_trunc('hour', now() + (i * 6 || ' hours')::interval), 
        date_trunc('hour', now() + (i * 6 || ' hours')::interval) + interval '2 hours', 
        0.00, 
        0.00, 
        'confirmed'
      );
    END LOOP;
  END IF;

  SELECT id INTO am_id FROM public.amenities WHERE society_id = v_society_id AND name = 'Gym' LIMIT 1;
  IF am_id IS NOT NULL THEN
    FOR i IN 1..5 LOOP
      SELECT flat_id, profile_id INTO f_id, v_user_id FROM public.flat_residents ORDER BY random() LIMIT 1;
      INSERT INTO public.amenity_bookings (amenity_id, profile_id, flat_id, start_at, end_at, total_amount, deposit, status)
      VALUES (
        am_id, 
        v_user_id, 
        f_id, 
        date_trunc('hour', now() + (i * 12 || ' hours')::interval), 
        date_trunc('hour', now() + (i * 12 || ' hours')::interval) + interval '1 hour', 
        0.00, 
        0.00, 
        'confirmed'
      );
    END LOOP;
  END IF;

  -- 11. Generate Complaints (10 entries with status updates)
  FOR i IN 1..10 LOOP
    SELECT flat_id, profile_id INTO f_id, v_user_id FROM public.flat_residents ORDER BY random() LIMIT 1;
    
    v_title := (ARRAY['Leaking tap in master bathroom', 'Power socket not working in kitchen', 'Stray dogs inside tower entrance', 'Elevator making strange noise', 'Improper parking by neighbor', 'Garbage collection missed today'])[1 + floor(random() * 6)::int];
    v_category := (ARRAY['Plumbing', 'Electrical', 'Security', 'Lift', 'Parking', 'Cleanliness'])[1 + floor(random() * 6)::int];
    v_desc := 'This is a test complaint description regarding ' || lower(v_title) || '. Please resolve this at the earliest.';
    v_priority := (ARRAY['low', 'medium', 'high', 'urgent'])[1 + floor(random() * 4)::int]::complaint_priority;
    v_status := (ARRAY['new', 'assigned', 'in_progress', 'resolved', 'closed'])[1 + floor(random() * 5)::int]::complaint_status;
    
    v_admin_id := CASE WHEN v_status <> 'new' THEN admin_profile_ids[1 + floor(random() * 2)::int] ELSE NULL END;
    
    INSERT INTO public.complaints (
      society_id, flat_id, raised_by, category, title, description, priority, status, assigned_to, created_at, resolved_at
    ) VALUES (
      v_society_id,
      f_id,
      v_user_id,
      v_category,
      v_title,
      v_desc,
      v_priority,
      v_status,
      v_admin_id,
      now() - (i || ' days')::interval,
      CASE WHEN v_status IN ('resolved', 'closed') THEN now() - (i - 1 || ' days')::interval ELSE NULL END
    ) RETURNING id INTO c_id;
    
    IF v_status <> 'new' THEN
      INSERT INTO public.complaint_updates (complaint_id, profile_id, body, kind, created_at)
      VALUES (c_id, admin_profile_ids[1], 'Assigned to manager for review.', 'status_change', now() - (i || ' days')::interval + interval '1 hour');
    END IF;
    
    IF v_status IN ('in_progress', 'resolved', 'closed') THEN
      INSERT INTO public.complaint_updates (complaint_id, profile_id, body, kind, created_at)
      VALUES (c_id, admin_profile_ids[1], 'Technician has been scheduled to visit.', 'comment', now() - (i || ' days')::interval + interval '4 hours');
    END IF;

    IF v_status IN ('resolved', 'closed') THEN
      INSERT INTO public.complaint_updates (complaint_id, profile_id, body, kind, created_at)
      VALUES (c_id, admin_profile_ids[1], 'Issue has been fixed by the maintenance team. Verified by technician.', 'status_change', now() - (i - 1 || ' days')::interval);
      
      INSERT INTO public.complaint_updates (complaint_id, profile_id, body, kind, created_at)
      VALUES (c_id, v_user_id, 'Thank you for the quick resolution!', 'comment', now() - (i - 1 || ' days')::interval + interval '1 hour');
    END IF;
  END LOOP;

  -- 12. Generate Dues and Payments (Last 3 months: May, June, July 2026)
  FOR i IN 1..least(60, flat_count) LOOP
    f_id := flat_ids[i];
    SELECT profile_id INTO v_user_id FROM public.flat_residents WHERE flat_id = f_id AND is_head = true LIMIT 1;
    
    IF v_user_id IS NOT NULL THEN
      FOR m_idx IN 0..2 LOOP
        v_period := ('2026-05-01'::date + (m_idx || ' months')::interval)::date;
        v_due_date := v_period + interval '10 days';
        
        v_electricity := 800.00 + floor(random() * 1200.00)::numeric;
        v_maintenance := 2500.00;
        v_total_amount := v_maintenance + v_electricity;
        
        v_line_items := jsonb_build_array(
          jsonb_build_object('name', 'Monthly Maintenance Charge', 'amount', v_maintenance),
          jsonb_build_object('name', 'Electricity Reading Charge', 'amount', v_electricity)
        );
        
        IF m_idx = 0 THEN
          v_due_status := 'paid';
        ELSIF m_idx = 1 THEN
          v_due_status := CASE WHEN random() < 0.85 THEN 'paid'::dues_status ELSE 'overdue'::dues_status END;
        ELSE
          v_due_status := CASE WHEN random() < 0.4 THEN 'paid'::dues_status ELSE 'due'::dues_status END;
        END IF;
        
        IF v_due_status = 'paid' THEN
          v_payment_id := gen_random_uuid();
          v_order_id := 'order_' || substring(md5(random()::text) from 1 for 12);
          v_razorpay_id := 'pay_' || substring(md5(random()::text) from 1 for 14);
          
          INSERT INTO public.payments (
            id, society_id, profile_id, order_id, razorpay_payment_id, amount, purpose, status, created_at, captured_at
          ) VALUES (
            v_payment_id,
            v_society_id,
            v_user_id,
            v_order_id,
            v_razorpay_id,
            v_total_amount,
            'dues',
            'captured',
            v_due_date - interval '2 days',
            v_due_date - interval '2 days'
          );
          
          INSERT INTO public.dues (
            society_id, flat_id, period, line_items, total, due_date, status, paid_at, payment_id
          ) VALUES (
            v_society_id,
            f_id,
            v_period,
            v_line_items,
            v_total_amount,
            v_due_date,
            'paid',
            v_due_date - interval '2 days',
            v_payment_id
          ) ON CONFLICT (flat_id, period) DO UPDATE
            SET status = 'paid', paid_at = excluded.paid_at, payment_id = excluded.payment_id, total = excluded.total;
        ELSE
          INSERT INTO public.dues (
            society_id, flat_id, period, line_items, total, due_date, status
          ) VALUES (
            v_society_id,
            f_id,
            v_period,
            v_line_items,
            v_total_amount,
            v_due_date,
            v_due_status
          ) ON CONFLICT (flat_id, period) DO UPDATE
            SET status = excluded.status, total = excluded.total;
        END IF;
      END LOOP;
    END IF;
  END LOOP;

  -- 13. Generate SOS Alerts (1 active, 1 resolved)
  SELECT flat_id, profile_id INTO f_id, v_user_id FROM public.flat_residents ORDER BY random() LIMIT 1;
  INSERT INTO public.sos_alerts (society_id, flat_id, created_by, status)
  VALUES (v_society_id, f_id, v_user_id, 'active');

  SELECT flat_id, profile_id INTO f_id, v_user_id FROM public.flat_residents ORDER BY random() LIMIT 1;
  INSERT INTO public.sos_alerts (society_id, flat_id, created_by, status, resolved_by, resolved_at, created_at)
  VALUES (
    v_society_id, 
    f_id, 
    v_user_id, 
    'resolved', 
    guard_profile_ids[1], 
    now() - interval '10 minutes', 
    now() - interval '25 minutes'
  );

END $$;

COMMIT;
